// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;

namespace Polytoria.SourceGen;

[Generator]
public sealed class ScriptEnumGenerator : IIncrementalGenerator
{
	private const string AttributeFullName = "Polytoria.Attributes.ScriptEnumAttribute";

	private static readonly DiagnosticDescriptor _duplicateScriptNameRule = new(
#pragma warning disable RS2008 // Enable analyzer release tracking
		id: "PTG0001",
#pragma warning restore RS2008 // Enable analyzer release tracking
		title: "Conflicting enum name",
		messageFormat: "Enum name '{0}' is already taken. Use ScriptEnum(\"name\") to provide a unique name.",
		category: "Polytoria.SourceGen",
		defaultSeverity: DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var enumSymbols = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				AttributeFullName,
				predicate: static (node, _) => node is EnumDeclarationSyntax,
				transform: static (ctx, _) =>
				{
					var enumSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
					var attrData = ctx.Attributes[0];

					var location = enumSymbol.Locations.Length > 0
						? enumSymbol.Locations[0]
						: Location.None;

					return new EnumEntry(
						GetScriptName(enumSymbol, attrData),
						enumSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
						GetIsCreatorOnly(attrData),
						location);
				})
			.Collect();

		context.RegisterSourceOutput(enumSymbols, static (spc, entries) =>
		{
			if (ReportDuplicates(spc, entries))
				return;

			spc.AddSource("ScriptEnumMapInitializer.g.cs", SourceText.From(GenerateEnumMapSource(entries), Encoding.UTF8));
		});
	}

	private static bool ReportDuplicates(SourceProductionContext spc, ImmutableArray<EnumEntry> entries)
	{
		var seen = new Dictionary<string, Location>(StringComparer.Ordinal);
		bool any = false;

		foreach (var entry in entries)
		{
			if (seen.TryGetValue(entry.ScriptName, out var firstLocation))
			{
				spc.ReportDiagnostic(Diagnostic.Create(_duplicateScriptNameRule, entry.Location, entry.ScriptName));

				if (firstLocation != Location.None)
				{
					spc.ReportDiagnostic(Diagnostic.Create(_duplicateScriptNameRule, firstLocation, entry.ScriptName));
					seen[entry.ScriptName] = Location.None;
				}

				any = true;
			}
			else
			{
				seen[entry.ScriptName] = entry.Location;
			}
		}

		return any;
	}

	private static string GetScriptName(INamedTypeSymbol enumSymbol, AttributeData attrData)
	{
		foreach (var namedArg in attrData.NamedArguments)
		{
			if (namedArg.Key == "Name" &&
				namedArg.Value.Value is string namedName &&
				!string.IsNullOrWhiteSpace(namedName))
				return namedName;
		}

		if (attrData.ConstructorArguments.Length > 0 &&
			attrData.ConstructorArguments[0].Value is string positionalName &&
			!string.IsNullOrWhiteSpace(positionalName))
			return positionalName;

		const string suffix = "Enum";
		var typeName = enumSymbol.Name;
		if (typeName.EndsWith(suffix, StringComparison.Ordinal) && typeName.Length > suffix.Length)
			return typeName.Substring(0, typeName.Length - suffix.Length);

		return typeName;
	}

	private static bool GetIsCreatorOnly(AttributeData attrData) =>
		attrData.NamedArguments.Any(a => a.Key == "IsCreatorOnly" && a.Value.Value is true);

	private static string GenerateEnumMapSource(ImmutableArray<EnumEntry> entries)
	{
		var regular = new List<EnumEntry>();
		var creatorOnly = new List<EnumEntry>();

		foreach (var entry in entries)
		{
			if (entry.IsCreatorOnly)
				creatorOnly.Add(entry);
			else
				regular.Add(entry);
		}

		var sb = new StringBuilder();
		using var stringWriter = new StringWriter(sb);
		using var writer = new IndentedTextWriter(stringWriter);

		writer.WriteLine("// <auto-generated/>");
		writer.WriteLine("#nullable enable");
		writer.WriteLine("using System;");
		writer.WriteLine("using System.Collections.Generic;");
		writer.WriteLine();
		writer.WriteLine("namespace Polytoria.Datamodel.Services;");
		writer.WriteLine();
		writer.WriteLine("internal static class ScriptEnumMapInitializer");
		writer.WriteLine("{");
		writer.Indent++;
		writer.WriteLine("public static readonly Dictionary<string, Type> EnumMap = new()");
		writer.WriteLine("{");
		writer.Indent++;

		foreach (var entry in regular)
			writer.WriteLine($"{{ \"{entry.ScriptName}\", typeof({entry.FullTypeRef}) }},");

		if (creatorOnly.Count > 0)
		{
			var savedIndent = writer.Indent;
			writer.Indent = 0;
			writer.WriteLine("#if CREATOR");
			writer.Indent = savedIndent;

			foreach (var entry in creatorOnly)
				writer.WriteLine($"{{ \"{entry.ScriptName}\", typeof({entry.FullTypeRef}) }},");

			writer.Indent = 0;
			writer.WriteLine("#endif");
			writer.Indent = savedIndent;
		}

		writer.Indent--;
		writer.WriteLine("};");
		writer.Indent--;
		writer.WriteLine("}");

		return sb.ToString();
	}

	private readonly struct EnumEntry(string scriptName, string fullTypeRef, bool isCreatorOnly, Location location)
	{
		public readonly string ScriptName = scriptName;
		public readonly string FullTypeRef = fullTypeRef;
		public readonly bool IsCreatorOnly = isCreatorOnly;
		public readonly Location Location = location;
	}
}
